# Generated by Django 5.2.15 on 2026-06-25 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        ('visitors', '0002_visitor_blacklisted_at_visitor_blacklisted_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('OVERSTAY', 'Overstay')], default='PENDING', max_length=20)),
                ('purpose', models.TextField(blank=True)),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('qr_code_image', models.TextField(blank=True)),
                ('qr_generated_at', models.DateTimeField(blank=True, null=True)),
                ('qr_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expected_duration', models.IntegerField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('host_responded_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('overstay_flagged', models.BooleanField(default=False)),
                ('overstay_flagged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_visits', to=settings.AUTH_USER_MODEL)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_performed', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_visits', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='organisations.organisation')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_visits', to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor')),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='visits_visi_status_ae8d13_idx'), models.Index(fields=['organisation'], name='visits_visi_organis_37b0e0_idx'), models.Index(fields=['scheduled_time'], name='visits_visi_schedul_b3ca73_idx'), models.Index(fields=['qr_code_token'], name='visits_visi_qr_code_e3c687_idx')],
            },
        ),
    ]
