# Generated by Django 5.2.15 on 2026-06-25 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('VISIT_CREATED', 'Visit Created'), ('VISIT_APPROVED', 'Visit Approved'), ('VISIT_REJECTED', 'Visit Rejected'), ('VISIT_CANCELLED', 'Visit Cancelled'), ('VISIT_EXPIRED', 'Visit Expired'), ('VISIT_CHECKED_IN', 'Visit Checked In'), ('VISIT_CHECKED_OUT', 'Visit Checked Out'), ('VISIT_OVERSTAY_FLAGGED', 'Visit Overstay Flagged'), ('VISITOR_CREATED', 'Visitor Created'), ('VISITOR_UPDATED', 'Visitor Updated'), ('VISITOR_BLACKLISTED', 'Visitor Blacklisted'), ('VISITOR_UNBLACKLISTED', 'Visitor Unblacklisted'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('ORG_SETTINGS_UPDATED', 'Organisation Settings Updated'), ('EMERGENCY_LOCKDOWN_ACTIVATED', 'Emergency Lockdown Activated'), ('EMERGENCY_LOCKDOWN_DEACTIVATED', 'Emergency Lockdown Deactivated'), ('QR_GENERATED', 'QR Generated'), ('QR_SCANNED', 'QR Scanned'), ('QR_INVALID', 'QR Invalid'), ('QR_EXPIRED', 'QR Expired')], max_length=50)),
                ('target_model', models.CharField(blank=True, max_length=50)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organisation'], name='auditlogs_a_organis_09c026_idx'), models.Index(fields=['action'], name='auditlogs_a_action_b1f2ec_idx'), models.Index(fields=['actor'], name='auditlogs_a_actor_i_0ee617_idx'), models.Index(fields=['target_model', 'target_id'], name='auditlogs_a_target__f518a1_idx')],
            },
        ),
    ]
