# Generated by Django 5.2.15 on 2026-06-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VISIT_CREATED', 'Visit Created'), ('VISIT_APPROVED', 'Visit Approved'), ('VISIT_REJECTED', 'Visit Rejected'), ('VISIT_CANCELLED', 'Visit Cancelled'), ('VISIT_EXPIRED', 'Visit Expired'), ('VISIT_CHECKED_IN', 'Visit Checked In'), ('VISIT_CHECKED_OUT', 'Visit Checked Out'), ('VISIT_OVERSTAY_FLAGGED', 'Visit Overstay Flagged'), ('NOTES_ADDED', 'Notes Added'), ('VISITOR_CREATED', 'Visitor Created'), ('VISITOR_UPDATED', 'Visitor Updated'), ('VISITOR_BLACKLISTED', 'Visitor Blacklisted'), ('VISITOR_UNBLACKLISTED', 'Visitor Unblacklisted'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('ORG_SETTINGS_UPDATED', 'Organisation Settings Updated'), ('EMERGENCY_LOCKDOWN_ACTIVATED', 'Emergency Lockdown Activated'), ('EMERGENCY_LOCKDOWN_DEACTIVATED', 'Emergency Lockdown Deactivated'), ('QR_GENERATED', 'QR Generated'), ('QR_SCANNED', 'QR Scanned'), ('QR_INVALID', 'QR Invalid'), ('QR_EXPIRED', 'QR Expired')], max_length=50),
        ),
    ]
