# Generated by Django 5.2.15 on 2026-06-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
            },
        ),
        migrations.CreateModel(
            name='OrganisationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_visit_duration', models.IntegerField(default=60)),
                ('require_host_approval', models.BooleanField(default=True)),
                ('notify_host_on_checkin', models.BooleanField(default=True)),
                ('allow_multiple_active_visits', models.BooleanField(default=False)),
                ('notify_before_expiry_minutes', models.IntegerField(default=15)),
                ('overstay_grace_period_minutes', models.IntegerField(default=5)),
                ('emergency_lockdown', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Organisation Setting',
                'verbose_name_plural': 'Organisation Settings',
            },
        ),
    ]
