# Generated by Django 5.2.15 on 2026-06-08 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='organisations.organisation')),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'indexes': [models.Index(fields=['email'], name='visitors_vi_email_e17823_idx'), models.Index(fields=['phone_number'], name='visitors_vi_phone_n_f99e12_idx')],
                'constraints': [models.UniqueConstraint(fields=('email', 'organisation'), name='unique_email_per_organisation'), models.UniqueConstraint(fields=('phone_number', 'organisation'), name='unique_phone_per_organisation')],
            },
        ),
    ]
