# Generated by Django 5.2.15 on 2026-06-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='blacklisted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='blacklisted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blacklisted_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='blacklisted_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
    ]
