# Generated by Django 5.2.15 on 2026-06-25 19:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('VISIT_CREATED', 'Visit Created'), ('VISIT_APPROVED', 'Visit Approved'), ('VISIT_REJECTED', 'Visit Rejected'), ('VISITOR_CHECKED_IN', 'Visitor Checked In'), ('VISITOR_CHECKED_OUT', 'Visitor Checked Out'), ('VISIT_OVERSTAY', 'Visit Overstay'), ('VISIT_CANCELLED', 'Visit Cancelled'), ('VISIT_EXPIRED', 'Visit Expired'), ('VISITOR_BLACKLISTED', 'Visitor Blacklisted')], max_length=30)),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('EMAIL', 'Email')], default='IN_APP', max_length=10)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('message', models.TextField()),
                ('failed_reason', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organisations.organisation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
