# Generated by Django 5.2.15 on 2026-06-25 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visits.visit'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organisation'], name='notificatio_organis_7d5943_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['delivery_status'], name='notificatio_deliver_455c3d_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['channel'], name='notificatio_channel_1d6e5f_idx'),
        ),
    ]
